"""
Plotter for Trust and Weight Logger

Interactive script used to plot `trust_weight_log_V*.csv` generated by `trust_logger.py`.

Three separate figures with GridSpec layout:
  Figure 1 – Trust Calculation (component scores, local/global, final trust, flags)
  Figure 2 – Weight Calculation  (w0, w_self, w_neighbor, summary metrics)
  Figure 3 – State Estimation     (estimated states, confidence, prediction mode)
  Figure 4 – Max Impact Histograms
  Figure 5 – V2V Detailed Tracking (per-vehicle distances and element values)
"""

import os
import glob
import re
import math
import csv
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import argparse

# python plot_trust_data.py --file ".\trust_weight_log_V1.csv" --relative-file "..\Relative_obs\relative_uio_log_V1.csv"

# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────

def _load_csv(filepath: str) -> Tuple[List[str], List[Dict[str, str]]]:
    """Return (columns, rows-as-dicts) from a CSV file, filtering corrupt lines."""
    cleaned_lines = []
    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            # Remove null bytes which can result from abrupt process termination
            line = line.replace('\x00', '')
            # Skip any lines that are still absurdly long (corrupted)
            if len(line) < 131072:
                cleaned_lines.append(line)
                
    reader = csv.DictReader(cleaned_lines)
    columns = reader.fieldnames or []
    rows = list(reader)
    return columns, rows


def _col_to_array(rows: List[dict], col: str) -> np.ndarray:
    """Convert a column to a float numpy array (NaN for missing/bad)."""
    vals = []
    for row in rows:
        raw = row.get(col, "")
        try:
            vals.append(float(raw))
        except (ValueError, TypeError):
            vals.append(float("nan"))
    return np.array(vals, dtype=float)


def _extract_vehicle_ids(columns: List[str]) -> List[int]:
    ids = set()
    prefixes = {
        "vehicle_present", "trust", "gtrust", "w_neighbor",
        "est_conf", "pred_mode", "est_x", "est_v",
        "v_score", "d_score", "a_score", "h_score",
        "b_score", "q_factor", "local_trust", "global_trust",
        "gamma_host", "gamma_local_peer", "gamma_self",
        "d_host_mean", "d_local_mean", "d_self",
        "mi_dist", "mi_veh_id", "mi_elem_idx", "mi_elem_val",
    }
    for col in columns:
        m = re.search(r"_(\d+)$", col)
        if m and col[: m.start()] in prefixes:
            ids.add(int(m.group(1)))
    return sorted(ids)


def _active_vehicles(rows: List[dict], columns: List[str],
                     vehicle_ids: List[int]) -> List[int]:
    active = []
    for vid in vehicle_ids:
        for prefix in ("vehicle_present", "trust", "gtrust",
                       "w_neighbor", "est_conf", "est_x"):
            col = f"{prefix}_{vid}"
            if col not in columns:
                continue
            arr = _col_to_array(rows, col)
            if prefix == "vehicle_present" and np.nanmax(arr) > 0:
                active.append(vid)
                break
            elif prefix != "vehicle_present" and np.any(np.isfinite(arr)):
                active.append(vid)
                break
    return active


def _plot_series(ax, times, rows, prefix, vids, label_fmt="Vehicle {}",
                 **kwargs):
    """Plot one series per vehicle. Returns count of plotted curves."""
    n = 0
    for vid in vids:
        col = f"{prefix}_{vid}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label_fmt.format(vid), **kwargs)
            n += 1
    return n


def _no_data(ax, title: str):
    ax.set_title(title, fontsize=10, fontweight="bold")
    ax.text(0.5, 0.5, "No data", ha="center", va="center",
            transform=ax.transAxes, fontsize=11, color="#888")


def _style(ax, title="", ylabel="", xlabel="", legend=True):
    if title:
        ax.set_title(title, fontsize=10, fontweight="bold")
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=9)
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=9)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.tick_params(labelsize=8)
    if legend:
        handles, labels = ax.get_legend_handles_labels()
        if handles:
            # Avoid duplicate legend entries for Turn Section if plotted multiple times
            by_label = dict(zip(labels, handles))
            ax.legend(by_label.values(), by_label.keys(), fontsize=7, ncol=max(1, len(by_label) // 2),
                      loc="best", framealpha=0.7)

def _add_turn_sections(ax, times, rows):
    is_turning = _col_to_array(rows, "is_turning")
    if np.any(np.isfinite(is_turning)) and np.any(is_turning > 0):
        import matplotlib.transforms as mtransforms
        trans = mtransforms.blended_transform_factory(ax.transData, ax.transAxes)
        ax.fill_between(times, 0, 1, where=(is_turning >= 1), color='gold', alpha=0.25, transform=trans, label='Turn Section')


def _yolo_usage_mask(rows: List[dict], vid: int) -> np.ndarray:
    """Return boolean mask where YOLO relative measurement was used for global trust."""
    yolo_flag = _col_to_array(rows, f"yolo_rel_meas_used_global_{vid}")
    if not np.any(np.isfinite(yolo_flag)):
        return np.zeros(len(rows), dtype=bool)
    return np.isfinite(yolo_flag) & (yolo_flag >= 0.5)


def _find_relative_uio_log(directory: str, host_id: int) -> str:
    """Return the matching relative UIO log for a host vehicle, if present."""
    if host_id < 0:
        return ""
    candidate_dirs = [
        directory,
        os.path.abspath(os.path.join(directory, "..", "Relative_obs")),
    ]
    matches = []
    for candidate_dir in candidate_dirs:
        pattern = os.path.join(candidate_dir, f"relative_uio_log_V{host_id}*.csv")
        matches.extend(glob.glob(pattern))
    matches = sorted(set(matches), key=os.path.getmtime)
    return matches[-1] if matches else ""

# ──────────────────────────────────────────────────────────────────────
# Figure builders
# ──────────────────────────────────────────────────────────────────────

def _fig_trust(times, rows, active, focus, host_id):
    """
    Figure 1 - Trust Calculation
    Layout (3 rows x 4 cols):
      [0,0] Direct trust                      [0,1] Generalized trust O_i(j)  [0,2] Local trust               [0,3] Global trust
      [1,0] Component scores (focus vehicle)  [1,1] Global trust factors      [1,2] Mahalanobis distances     [1,3] Attack flags
      [2,0] Relative distance comparison       [2,1] 
      [2,2] YOLO-vs-true relative errors       [2,3] Relative measurement usage flags
    """
    fig = plt.figure(figsize=(24, 12))
    fig.suptitle(f"Trust Calculation  (Host V{host_id})", fontsize=15,
                 fontweight="bold")
    gs = gridspec.GridSpec(3, 4, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) Direct trust
    ax = fig.add_subplot(gs[0, 0])
    if _plot_series(ax, times, rows, "trust", active) == 0:
        _no_data(ax, "Direct Trust Score")
    ax.axhline(0.5, color="r", ls=":", lw=0.8, alpha=0.6, label="threshold")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Direct Trust Score", "Trust [0,1]")

    # (0,1) Generalized trust
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "gtrust", active) == 0:
        _no_data(ax, "Generalized Trust O_i(j)")
    ax.axhline(0.5, color="r", ls=":", lw=0.8, alpha=0.6)
    _add_turn_sections(ax, times, rows)
    _style(ax, "Generalized Trust O_i(j)", "Trust [0,1]")

    # (0,2) Local trust
    ax = fig.add_subplot(gs[0, 2])
    if _plot_series(ax, times, rows, "local_trust", active,
                    label_fmt="LT V{}") == 0:
        _no_data(ax, "Local Trust (gamma_local)")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Local Trust (gamma_local)", "Trust [0,1]")

    # (0,3) Global trust
    ax = fig.add_subplot(gs[0, 3])
    if _plot_series(ax, times, rows, "global_trust", active,
                    label_fmt="GT V{}") == 0:
        _no_data(ax, "Global Trust (gamma_cross)")
    _add_turn_sections(ax, times, rows)
    _style(ax, "Global Trust (gamma_cross)", "Trust [0,1]")

    # (1,0) Trust components for focus vehicle
    ax = fig.add_subplot(gs[1, 0])
    comp = [
        (f"v_score_{focus}", "Velocity"),
        (f"d_score_{focus}", "Distance"),
        (f"a_score_{focus}", "Acceleration"),
        (f"h_score_{focus}", "Heading"),
        (f"b_score_{focus}", "Beacon"),
        (f"q_factor_{focus}", "Quality"),
    ]
    n = 0
    for col, lbl in comp:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Component Scores (V{focus})")
    _style(ax, f"Component Scores (V{focus})", "Score [0,1]")

    # (1,1) Global trust factors for focus vehicle
    ax = fig.add_subplot(gs[1, 1])
    gamma_cols = [
        (f"gamma_host_{focus}", "gamma_host"),
        (f"gamma_local_peer_{focus}", "gamma_local_peer"),
        (f"gamma_self_{focus}", "gamma_self"),
        (f"global_trust_{focus}", "global_trust"),
    ]
    n = 0
    for col, lbl in gamma_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Global Trust Factors (V{focus})")
    _style(ax, f"Global Trust Factors (V{focus})", "Value [0,1]")

    # (1,2) Mahalanobis distance terms for focus vehicle
    ax = fig.add_subplot(gs[1, 2])
    dist_cols = [
        (f"d_host_mean_{focus}", "d_host_mean"),
        (f"d_local_mean_{focus}", "d_local_mean"),
        (f"d_self_{focus}", "d_self"),
    ]
    n = 0
    for col, lbl in dist_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Mahalanobis Distances (V{focus})")
    _style(ax, f"Mahalanobis Distances (V{focus})", "Distance", xlabel="Time [s]")

    # (1,3) Attack flags for focus vehicle
    ax = fig.add_subplot(gs[1, 3])
    flag_cols = [
        (f"flag_attack_{focus}", "Target Attack"),
        (f"flag_local_{focus}", "Local Est Check"),
        (f"flag_global_{focus}", "Global Est Check"),
    ]
    n = 0
    offsets = [0.0, 0.05, 0.10]
    for (col, lbl), off in zip(flag_cols, offsets):
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.fill_between(times, off, arr + off, alpha=0.5, step="post",
                            label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Attack Flags (V{focus})")
    _style(ax, f"Attack Flags (V{focus})", "Flag", xlabel="Time [s]")

    # (2,0) Relative distance comparison for focus vehicle
    ax = fig.add_subplot(gs[2, 0])
    n = 0
    rel_dist_cols = [
        (f"y_local_distance_{focus}", "Local rel dist"),
        (f"y_true_distance_{focus}", "True rel dist (fallback)"),
        (f"yolo_rel_distance_{focus}", "YOLO rel dist"),
    ]
    for col, lbl in rel_dist_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            style = "-" if "YOLO" in lbl else "--"
            ax.plot(times, arr, style, lw=1.3, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Relative Distance (V{focus})")
    _style(ax, f"Relative Distance (V{focus})", "Distance [m]", xlabel="Time [s]")

    # (2,1) Max Impact Element
    ax = fig.add_subplot(gs[2, 1])
    arr_idx = _col_to_array(rows, f"mi_elem_idx_{focus}")
    arr_val = _col_to_array(rows, f"mi_elem_val_{focus}")
    if np.any(np.isfinite(arr_idx)) and np.any(np.isfinite(arr_val)):
        ax.plot(times, arr_val, label="Max Element Value", color="tab:orange", lw=1.5)
        ax2 = ax.twinx()
        valid_idx = np.isfinite(arr_idx)
        ax2.scatter(np.array(times)[valid_idx], arr_idx[valid_idx], s=10, c="tab:green", alpha=0.5, label="Element Index")
        # use descriptive tick labels instead of raw numbers
        ax2.set_ylabel("Impact Element", fontsize=8)
        ticks = [0, 1, 2, 3, 4]
        labels = ["x", "y", "theta", "v", "a"]
        ax2.set_yticks(ticks)
        ax2.set_yticklabels(labels)
        
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, loc="upper right", fontsize=7)
    else:
        _no_data(ax, f"Max Impact Element (V{focus})")
    _style(ax, f"Max Impact Element Index & Score (V{focus})", "Contribution / Score", xlabel="Time [s]", legend=False)

    # (2,2) YOLO-vs-true errors
    ax = fig.add_subplot(gs[2, 2])
    n = 0
    err_cols = [
        (f"yolo_true_rel_dist_error_{focus}", "YOLO-True dist error"),
        (f"yolo_true_rel_vel_error_{focus}", "YOLO-True rel vel error"),
    ]
    for col, lbl in err_cols:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, lw=1.3, label=lbl)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, f"YOLO vs True Error (V{focus})")
    _style(ax, f"YOLO vs True Error (V{focus})", "Error", xlabel="Time [s]")

    # (2,3) Relative measurement usage flags
    ax = fig.add_subplot(gs[2, 3])
    n = 0
    flag_cols = [
        (f"rel_meas_used_global_{focus}", "Any external rel used"),
        (f"yolo_rel_meas_used_global_{focus}", "YOLO rel used"),
        (f"rel_dist_meas_used_{focus}", "External dist used"),
        (f"rel_vel_meas_used_{focus}", "External rel vel used"),
    ]
    offsets = [0.00, 0.08, 0.16, 0.24]
    for (col, lbl), off in zip(flag_cols, offsets):
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.fill_between(times, off, arr + off, alpha=0.5, step="post", label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, f"Relative Measurement Usage (V{focus})")
    _style(ax, f"Relative Measurement Usage (V{focus})", "Flag", xlabel="Time [s]")

    return fig


def _fig_weights(times, rows, active, host_id):
    """
    Figure 2 – Weight Calculation
    Layout (2 rows × 2 cols):
      [0,0] w0, w_self over time             [0,1] Per-neighbor weights
      [1,0] Mean trust metrics                [1,1] Trusted neighbor count
    """
    fig = plt.figure(figsize=(16, 7))
    fig.suptitle(f"Weight Calculation  (Host V{host_id})", fontsize=13,
                 fontweight="bold")
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) w0, w_self
    ax = fig.add_subplot(gs[0, 0])
    n = 0
    for col, lbl, ls in [("w0", "w0 (direct)", "-."),
                          ("w_self", "w_self", "--")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, ls, lw=1.5, label=lbl, color="k" if col == "w_self" else "tab:blue")
            n += 1
    total_arr = _col_to_array(rows, "total_neighbor_weight")
    if np.any(np.isfinite(total_arr)):
        ax.plot(times, total_arr, "-", lw=1.2, label="total_neighbor_w",
                color="tab:orange")
        n += 1
    if n == 0:
        _no_data(ax, "Fixed Weights")
    _style(ax, "Fixed Weights (w0, w_self)", "Weight")

    # (0,1) Per-neighbor weights
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "w_neighbor", active,
                    label_fmt="w_neighbor V{}") == 0:
        _no_data(ax, "Per-Neighbor Weights")
    _style(ax, "Per-Neighbor Weights", "Weight")

    # (1,0) Mean trust metrics
    ax = fig.add_subplot(gs[1, 0])
    n = 0
    for col, lbl in [("mean_direct_trust", "Mean Direct Trust"),
                      ("mean_generalized_trust", "Mean Generalized Trust"),
                      ("mean_gamma_host", "Mean gamma_host"),
                      ("mean_gamma_local_peer", "Mean gamma_local_peer"),
                      ("mean_gamma_self", "Mean gamma_self"),
                      ("weighted_neighbor_trust", "Weighted Neighbor Trust")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, "Trust Summary Metrics")
    _style(ax, "Trust Summary Metrics", "Value", xlabel="Time [s]")

    # (1,1) Trusted neighbor count
    ax = fig.add_subplot(gs[1, 1])
    n = 0
    for col, lbl in [("trusted_neighbor_count", "Trusted Neighbors"),
                      ("active_vehicle_count", "Active Vehicles")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.step(times, arr, where="post", label=lbl)
            n += 1
    if n == 0:
        _no_data(ax, "Neighbor Counts")
    _style(ax, "Neighbor / Active Vehicle Counts", "Count",
           xlabel="Time [s]")

    return fig


def _fig_estimation(times, rows, active, host_id):
    """
    Figure 3 – State Estimation
    Layout (4 rows × 2 cols):
      [0,0] Estimated X                      [0,1] Estimated Y
      [1,0] Estimated velocity               [1,1] Estimated acceleration
      [2,0] Estimated heading (theta)        [2,1] Trajectory XY
      [3,0] Estimation confidence + self_belief  [3,1] Prediction mode flags
    """
    fig = plt.figure(figsize=(16, 13))
    fig.suptitle(f"State Estimation  (Host V{host_id})", fontsize=13,
                 fontweight="bold")
    gs = gridspec.GridSpec(4, 2, figure=fig, hspace=0.35, wspace=0.25)

    # (0,0) Estimated X
    ax = fig.add_subplot(gs[0, 0])
    if _plot_series(ax, times, rows, "est_x", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated X")
    _style(ax, "Estimated X", "x [m]")

    # (0,1) Estimated Y
    ax = fig.add_subplot(gs[0, 1])
    if _plot_series(ax, times, rows, "est_y", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Y")
    _style(ax, "Estimated Y", "y [m]")

    # (1,0) Velocity
    ax = fig.add_subplot(gs[1, 0])
    if _plot_series(ax, times, rows, "est_v", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Velocity")
    _style(ax, "Estimated Velocity", "v [m/s]")

    # (1,1) Acceleration
    ax = fig.add_subplot(gs[1, 1])
    if _plot_series(ax, times, rows, "est_a", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Acceleration")
    _style(ax, "Estimated Acceleration", "a [m/s²]")

    # (2,0) Estimated Heading (theta)
    ax = fig.add_subplot(gs[2, 0])
    if _plot_series(ax, times, rows, "est_theta", active, label_fmt="V{}") == 0:
        _no_data(ax, "Estimated Heading")
    _style(ax, "Estimated Heading", "theta [rad]")

    # (2,1) Trajectory (XY)
    ax = fig.add_subplot(gs[2, 1])
    n = 0
    for vid in active:
        col_x = f"est_x_{vid}"
        col_y = f"est_y_{vid}"
        arr_x = _col_to_array(rows, col_x)
        arr_y = _col_to_array(rows, col_y)
        if np.any(np.isfinite(arr_x)) and np.any(np.isfinite(arr_y)):
            ax.plot(arr_x, arr_y, label=f"V{vid}")
            # Add a marker at the start
            idx = np.where(np.isfinite(arr_x) & np.isfinite(arr_y))[0]
            if len(idx) > 0:
                ax.plot(arr_x[idx[0]], arr_y[idx[0]], 'o', color=ax.lines[-1].get_color())
            n += 1
    if n == 0:
        _no_data(ax, "Trajectory XY")
    else:
        ax.axis("equal")
    _style(ax, "Trajectory XY", "y [m]", xlabel="x [m]")

    # (3,0) Confidence + self_belief
    ax = fig.add_subplot(gs[3, 0])
    n = _plot_series(ax, times, rows, "est_conf", active,
                     label_fmt="Conf V{}")
    for col, lbl, ls in [("self_belief", "self_belief", "--"),
                          ("platoon_conf_mean", "platoon_conf_mean", "-"),
                          ("platoon_conf_min", "platoon_conf_min", ":"),
                          ("platoon_conf_max", "platoon_conf_max", ":")]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, ls, lw=1.3, label=lbl, color="k")
            n += 1
    if n == 0:
        _no_data(ax, "Estimation Confidence")
    _style(ax, "Estimation Confidence", "Confidence", xlabel="Time [s]")

    # (3,1) Prediction mode flags
    ax = fig.add_subplot(gs[3, 1])
    n = 0
    for vid in active:
        col = f"pred_mode_{vid}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.step(times, arr, where="post", label=f"V{vid}")
            n += 1
    pred_count = _col_to_array(rows, "prediction_mode_count")
    if np.any(np.isfinite(pred_count)):
        ax.plot(times, pred_count, "k--", lw=1.3, label="total_pred_mode")
        n += 1
    if n == 0:
        _no_data(ax, "Prediction Mode")
    _style(ax, "Prediction Mode Flags", "Mode (0/1)", xlabel="Time [s]")

    return fig


def _fig_relative_uio(filepath: str, host_id: int):
    """
    Figure 6 - Relative UIO diagnostics from relative_uio_log_V*.csv.
    """
    columns, rows = _load_csv(filepath)
    if "time" not in columns or not rows:
        print(f"Relative UIO log has no plottable samples: {filepath}")
        return None

    times = _col_to_array(rows, "time")
    target_ids = _col_to_array(rows, "target_id")
    finite_targets = target_ids[np.isfinite(target_ids)]
    target_label = (
        f"V{int(finite_targets[-1])}" if finite_targets.size > 0 else "unknown target"
    )

    fig = plt.figure(figsize=(18, 18))
    fig.suptitle(
        f"Relative UIO Diagnostics  (Host V{host_id}, Target {target_label})",
        fontsize=13,
        fontweight="bold",
    )
    gs = gridspec.GridSpec(5, 2, figure=fig, hspace=0.35, wspace=0.25)

    # Kinematic state estimates
    ax = fig.add_subplot(gs[0, 0])
    n = 0
    for col, label in [
        ("delta_hat", "delta_hat"),
        ("delta_dot_hat", "delta_dot_hat"),
        ("delta_ddot_hat", "delta_ddot_hat"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "UIO Kinematic State Estimates")
    _style(ax, "UIO Kinematic State Estimates", "Estimate")

    # Distance estimate against measurements and V2V fallback
    ax = fig.add_subplot(gs[0, 1])
    n = 0
    for col, label, style in [
        ("delta_hat", "UIO distance estimate", "-"),
        ("measurement_distance", "Measured distance", "--"),
        ("v2v_fallback_distance", "V2V-derived distance", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Relative Distance")
    _style(ax, "Relative Distance", "Distance [m]")

    # Relative velocity estimate against measurements and V2V fallback
    ax = fig.add_subplot(gs[1, 0])
    n = 0
    for col, label, style in [
        ("delta_dot_hat", "UIO relative velocity", "-"),
        ("measurement_relative_velocity", "Measured relative velocity", "--"),
        ("v2v_fallback_relative_velocity", "V2V-derived relative velocity", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Relative Velocity")
    _style(ax, "Relative Velocity", "Velocity [m/s]")

    # Relative acceleration estimate against V2V-derived acceleration
    ax = fig.add_subplot(gs[1, 1])
    rel_acc_v2v = _col_to_array(rows, "v2v_fallback_relative_acceleration")
    if not np.any(np.isfinite(rel_acc_v2v)):
        target_acc = _col_to_array(rows, "target_state_4")
        host_acc = _col_to_array(rows, "host_state_4")
        if np.any(np.isfinite(target_acc)) and np.any(np.isfinite(host_acc)):
            rel_acc_v2v = target_acc - host_acc

    n = 0
    for arr, label, style in [
        (_col_to_array(rows, "delta_ddot_hat"), "UIO relative acceleration delta_ddot_hat", "-"),
        (rel_acc_v2v, "V2V-derived relative acceleration", ":"),
        (_col_to_array(rows, "target_acceleration_input"), "Target acceleration input", "--"),
    ]:
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, "Relative Acceleration")
    _style(ax, "Relative Acceleration Estimate", "Acceleration [m/s^2]")

    # Measurement / estimate errors against V2V-derived fallback
    ax = fig.add_subplot(gs[2, 0])
    n = 0
    rel_acc_error = _col_to_array(rows, "relative_acceleration_error_vs_v2v")
    if not np.any(np.isfinite(rel_acc_error)):
        delta_ddot = _col_to_array(rows, "delta_ddot_hat")
        if np.any(np.isfinite(delta_ddot)) and np.any(np.isfinite(rel_acc_v2v)):
            rel_acc_error = delta_ddot - rel_acc_v2v

    for arr, label in [
        (_col_to_array(rows, "distance_error_vs_v2v"), "Distance error"),
        (_col_to_array(rows, "relative_velocity_error_vs_v2v"), "Relative velocity error"),
        (rel_acc_error, "Relative acceleration error"),
    ]:
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n > 0:
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    if n == 0:
        _no_data(ax, "Measurement Error vs V2V")
    _style(ax, "Measurement Error vs V2V", "Error", xlabel="Time [s]")

    # Measurement availability/quality
    ax = fig.add_subplot(gs[2, 1])
    n = 0
    for col, label, style in [
        ("measurement_used", "Measurement used", "-"),
        ("measurement_confidence", "Measurement confidence", "--"),
        ("measurement_age_s", "Measurement age [s]", ":"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, style, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "Measurement Usage")
    _style(ax, "Measurement Usage / Quality", "Value", xlabel="Time [s]")

    # Inputs used by the observer
    ax = fig.add_subplot(gs[3, 0])
    n = 0
    for col, label in [
        ("host_velocity_input", "Host velocity input"),
        ("target_acceleration_input", "Target acceleration input"),
    ]:
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            ax.plot(times, arr, label=label)
            n += 1
    if n == 0:
        _no_data(ax, "UIO Inputs")
    _style(ax, "UIO Inputs", "Input", xlabel="Time [s]")

    # Unknown input / cyber-disturbance estimate separated from kinematics
    ax = fig.add_subplot(gs[3:5, 1])
    arr = _col_to_array(rows, "f_c_hat")
    if np.any(np.isfinite(arr)):
        ax.plot(times, arr, label="d_c_hat / f_c_hat", color="tab:red", lw=1.4)
        ax.axhline(0.0, color="k", ls=":", lw=0.8, alpha=0.6)
    else:
        _no_data(ax, "Unknown Input Estimate")
    _style(ax, "Unknown Input Estimate d_c_hat / f_c_hat", "Estimate", xlabel="Time [s]")

    return fig


def _fig_impact_histograms(rows, active, focus, host_id):
    """
    Figure 4 - Impact Overview Histograms
    Layout (1 row x 2 cols):
      [0,0] Max Impact Vehicle Frequency  [0,1] Max Impact Element Frequency
    """
    fig = plt.figure(figsize=(12, 5))
    fig.suptitle(f"Max Impact Overview (Host V{host_id}, Focus V{focus})", fontsize=13, fontweight="bold")
    gs = gridspec.GridSpec(1, 2, figure=fig, wspace=0.3)
    
    # [0,0] Max Impact Vehicle
    ax1 = fig.add_subplot(gs[0, 0])
    veh_col = _col_to_array(rows, f"mi_veh_id_{focus}")
    if np.any(np.isfinite(veh_col)):
        valid_vehs = veh_col[np.isfinite(veh_col)].astype(int)
        unique_vehs, counts = np.unique(valid_vehs, return_counts=True)
        ax1.bar([f"V{v}" for v in unique_vehs], counts, color="tab:blue", alpha=0.7)
        for i, count in enumerate(counts):
            ax1.text(i, count, str(count), ha="center", va="bottom", fontsize=9)
        ax1.set_ylabel("Frequency")
        ax1.set_title(f"Max Impact Vehicle Frequency (Focus V{focus})")
    else:
        _no_data(ax1, f"Max Impact Vehicle (V{focus})")
        
    # [0,1] Max Impact Element Index
    ax2 = fig.add_subplot(gs[0, 1])
    idx_col = _col_to_array(rows, f"mi_elem_idx_{focus}")
    if np.any(np.isfinite(idx_col)):
        valid_idxs = idx_col[np.isfinite(idx_col)].astype(int)
        unique_idxs, counts = np.unique(valid_idxs, return_counts=True)
        elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}
        labels = [elem_names.get(i, str(i)) for i in unique_idxs]
        ax2.bar(labels, counts, color="tab:orange", alpha=0.7)
        for i, count in enumerate(counts):
            ax2.text(i, count, str(count), ha="center", va="bottom", fontsize=9)
        ax2.set_ylabel("Frequency")
        ax2.set_title(f"Max Impact Element Frequency (Focus V{focus})")
    else:
        _no_data(ax2, f"Max Impact Element (V{focus})")

    fig.tight_layout(rect=[0, 0, 1, 0.95])
    return fig


def _fig_v2v_details(times, rows, active, focus, host_id):
    """
    Figure 5 - Detailed V2V Tracking for Global Trust
    Layout (2 rows x 2 cols):
      [0,0] Distance per evaluated vehicle    [0,1] Element Value per evaluated vehicle
      [1,0:2] Element Index per evaluated vehicle (Scatter)
    """
    fig = plt.figure(figsize=(14, 9))
    fig.suptitle(f"V2V Detailed Tracking (Host V{host_id} evaluating Focus V{focus})", fontsize=13, fontweight="bold")
    gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.25)

    # Find the k indices that have data
    available_k = []
    # Test up to 20 just in case
    for k in range(20):
        if _col_to_array(rows, f"g_dist_v{k}_{focus}").any():
            available_k.append(k)

    if not available_k:
        # Fallback if no detailed data
        ax = fig.add_subplot(gs[0, 0])
        _no_data(ax, "V2V Distance Tracking")
        return fig

    elem_markers = {0: 's', 1: 'D', 2: '^', 3: 'v', 4: 'o'}
    elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}

    # [0,0] Distances
    ax = fig.add_subplot(gs[0, 0])
    
    # Add dummy legend entries for marker shapes
    for idx, m in elem_markers.items():
        ax.plot([], [], color='gray', marker=m, linestyle='None', label=f"Impact: {elem_names[idx]}")

    n = 0
    for k in available_k:
        col_dist = f"g_dist_v{k}_{focus}"
        col_idx = f"g_idx_v{k}_{focus}"
        arr_dist = _col_to_array(rows, col_dist)
        arr_idx = _col_to_array(rows, col_idx)

        if np.any(np.isfinite(arr_dist)):
            p = ax.plot(times, arr_dist, label=f"V{k}")
            color = p[0].get_color()
            
            # Overlay markers indicating max impact element
            valid_mask = np.isfinite(arr_dist) & np.isfinite(arr_idx)
            if np.any(valid_mask):
                t_valid = np.array(times)[valid_mask]
                d_valid = arr_dist[valid_mask]
                i_valid = arr_idx[valid_mask].astype(int)
                
                for idx in np.unique(i_valid):
                    idx_mask = (i_valid == idx)
                    ax.scatter(t_valid[idx_mask], d_valid[idx_mask], color=color, marker=elem_markers.get(idx, 'o'), s=30, alpha=0.7, zorder=3)
            n += 1

    if n == 0:
        _no_data(ax, "V2V Distance")
    _style(ax, "Mahalanobis Distance per Vehicle", "Distance", xlabel="Time [s]")

    # [0,1] Element Values
    ax = fig.add_subplot(gs[0, 1])
    # Add dummy legend entries for marker shapes
    for idx, m in elem_markers.items():
        ax.plot([], [], color='gray', marker=m, linestyle='None', label=f"Impact: {elem_names[idx]}")

    n = 0
    for k in available_k:
        col_val = f"g_val_v{k}_{focus}"
        col_idx = f"g_idx_v{k}_{focus}"
        arr_val = _col_to_array(rows, col_val)
        arr_idx = _col_to_array(rows, col_idx)

        if np.any(np.isfinite(arr_val)):
            p = ax.plot(times, arr_val, label=f"V{k}")
            color = p[0].get_color()
            
            # Overlay markers indicating max impact element
            valid_mask = np.isfinite(arr_val) & np.isfinite(arr_idx)
            if np.any(valid_mask):
                t_valid = np.array(times)[valid_mask]
                v_valid = arr_val[valid_mask]
                i_valid = arr_idx[valid_mask].astype(int)
                
                for idx in np.unique(i_valid):
                    idx_mask = (i_valid == idx)
                    ax.scatter(t_valid[idx_mask], v_valid[idx_mask], color=color, marker=elem_markers.get(idx, 'o'), s=30, alpha=0.7, zorder=3)
            n += 1

    if n == 0:
        _no_data(ax, "V2V Element Value")
    _style(ax, "Max Impact Element Value per Vehicle", "Value", xlabel="Time [s]")

    # [1,0:2] Element Indices
    ax = fig.add_subplot(gs[1, 0:2])
    n = 0
    for k in available_k:
        col = f"g_idx_v{k}_{focus}"
        arr = _col_to_array(rows, col)
        if np.any(np.isfinite(arr)):
            valid_mask = np.isfinite(arr)
            ax.scatter(np.array(times)[valid_mask], arr[valid_mask], s=15, alpha=0.6, label=f"V{k}")
            n += 1

    if n == 0:
        _no_data(ax, "V2V Element Index")
    else:
        ax.set_yticks([0, 1, 2, 3, 4])
        ax.set_yticklabels(["x", "y", "theta", "v", "a"])
    _style(ax, "Max Impact Element Index per Vehicle", "Element", xlabel="Time [s]")

    return fig


def _print_static_metrics(rows, active):
    """
    Print an analytic summary of the trust logging run to the console.
    Helps tune parameters by surfacing the most common threshold breakers.
    """
    print("\n" + "="*80)
    print(f"{'STATIC METRICS DASHBOARD':^80}")
    print("="*80)
    
    elem_names = {0: "x", 1: "y", 2: "theta", 3: "v", 4: "a"}

    print(f"{'Vehicle':<10} | {'Target Atk':<12} | {'Local Est Bad':<15} | {'Global Est Bad':<16} | {'Max Impact Elements (Count)'}")
    print("-" * 80)

    for vid in active:
        # Tally attack flags
        target_atk_col = _col_to_array(rows, f"flag_attack_{vid}")
        local_est_col = _col_to_array(rows, f"flag_local_{vid}")
        global_est_col = _col_to_array(rows, f"flag_global_{vid}")
        
        target_atks = int(np.nansum(target_atk_col)) if np.any(np.isfinite(target_atk_col)) else 0
        local_bads = int(np.nansum(local_est_col)) if np.any(np.isfinite(local_est_col)) else 0
        global_bads = int(np.nansum(global_est_col)) if np.any(np.isfinite(global_est_col)) else 0
        
        # Determine element offenders
        elem_idx_col = _col_to_array(rows, f"mi_elem_idx_{vid}")
        dist_col = _col_to_array(rows, f"mi_dist_{vid}")
        
        elem_str = "None"
        if np.any(np.isfinite(elem_idx_col)):
            valid_idx = np.isfinite(elem_idx_col)
            valid_elems = elem_idx_col[valid_idx].astype(int)
            valid_dists = dist_col[valid_idx] if np.any(np.isfinite(dist_col)) else np.zeros_like(valid_elems)
            
            # Count the occurrences of each element being the max impact
            counts = {i: 0 for i in range(5)}
            dist_sums = {i: 0.0 for i in range(5)}
            
            for e, d in zip(valid_elems, valid_dists):
                if e in counts:
                    counts[e] += 1
                    dist_sums[e] += d
                    
            # Sort by count descending
            sorted_elems = sorted(counts.items(), key=lambda x: x[1], reverse=True)
            
            elem_strs = []
            for e, count in sorted_elems:
                if count > 0:
                    avg_d = dist_sums[e] / count
                    name = elem_names.get(e, str(e))
                    elem_strs.append(f"{name} ({count}x, avg dist: {avg_d:.2f})")
            
            if elem_strs:
                elem_str = ", ".join(elem_strs[:2]) # Show top 2
        
        print(f"V{vid:<9} | {target_atks:<12} | {local_bads:<15} | {global_bads:<16} | {elem_str}")

    print("="*80 + "\n")


def main():
    parser = argparse.ArgumentParser(
        description="Plot trust/weight logs."
    )
    parser.add_argument("--file", "-f", help="path to a specific CSV file to plot")
    parser.add_argument("--all", action="store_true",
                        help="generate figures for every candidate focus vehicle")
    parser.add_argument("--focus", type=int,
                        help="vehicle ID to use as focus (overrides interactive choice)")
    parser.add_argument("--relative-file",
                        help="path to a relative_uio_log_V*.csv file to plot")
    parser.add_argument("--skip-relative", action="store_true",
                        help="do not auto-load matching relative UIO log")
    args = parser.parse_args()

    directory = os.path.dirname(os.path.abspath(__file__))
    csv_files = sorted(glob.glob(os.path.join(directory,
                                              "trust_weight_log_V*.csv")))
    if not csv_files:
        print("No trust log files found in:", directory)
        return

    if args.file:
        file_to_plot = args.file
        if not os.path.isfile(file_to_plot):
            print(f"Specified file does not exist: {file_to_plot}")
            return
    else:
        print("Found files:")
        for i, f in enumerate(csv_files):
            print(f"[{i}] {os.path.basename(f)}")

        choice = input(f"Select file to plot [0-{len(csv_files) - 1}]: ").strip()
        try:
            choice = int(choice)
            file_to_plot = csv_files[choice]
        except (ValueError, IndexError):
            print("Invalid choice. Exiting.")
            return

    columns, rows = _load_csv(file_to_plot)
    if "time" not in columns:
        print("Invalid format: 'time' column missing.")
        return

    times = _col_to_array(rows, "time")
    vehicle_ids = _extract_vehicle_ids(columns)
    active = _active_vehicles(rows, columns, vehicle_ids)

    if not active:
        print("No active vehicle data found.")
        return

    # Determine host vehicle from filename
    host_match = re.search(r"V(\d+)\.csv$", os.path.basename(file_to_plot))
    host_id = int(host_match.group(1)) if host_match else -1

    # Determine list of candidate focus vehicles (exclude host if possible)
    neighbors = [v for v in active if v != host_id]
    focus_candidates = neighbors or active[:]

    print(f"Host vehicle: V{host_id}")
    print(f"Active vehicles: {active}")
    print(f"Candidate focus vehicles: {focus_candidates}")
    print(f"Total samples: {len(rows)}\n")

    # Print analytic summary
    _print_static_metrics(rows, active)

    # Choose focus vehicles according to command-line flags or interactive input
    if args.all:
        focuses = focus_candidates
    elif args.focus is not None:
        if args.focus in focus_candidates:
            focuses = [args.focus]
        else:
            print(f"Requested focus V{args.focus} not in candidate list; using {focus_candidates[0]}")
            focuses = [focus_candidates[0]]
    else:
        # interactive prompt if no CLI preference provided
        focus_selection = input(
            "Enter a focus vehicle ID from the list above, or type 'all' to generate a separate set of figures for every candidate (default = first): "
        ).strip().lower()

        if focus_selection == "all":
            focuses = focus_candidates
        else:
            try:
                fid = int(focus_selection)
                focuses = [fid] if fid in focus_candidates else [focus_candidates[0]]
            except ValueError:
                focuses = [focus_candidates[0]]

    # Build the figures (multiple sets if necessary)
    for focus in focuses:
        print(f"Plotting figures with focus vehicle: V{focus} ...")
        _fig_trust(times, rows, active, focus, host_id)
        _fig_weights(times, rows, active, host_id)
        _fig_estimation(times, rows, active, host_id)
        _fig_impact_histograms(rows, active, focus, host_id)
        _fig_v2v_details(times, rows, active, focus, host_id)

    if not args.skip_relative:
        relative_file = args.relative_file or _find_relative_uio_log(directory, host_id)
        if relative_file and os.path.isfile(relative_file):
            print(f"Plotting relative UIO diagnostics: {os.path.basename(relative_file)}")
            _fig_relative_uio(relative_file, host_id)
        elif args.relative_file:
            print(f"Specified relative UIO file does not exist: {args.relative_file}")

    plt.show()


if __name__ == "__main__":
    main()
